import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import {
  MatAutocompleteModule,
  MatButtonModule,
  MatCardModule,
  MatCheckboxModule,
  MatDialogModule,
  MatFormFieldModule,
  MatMenuModule,
  MatInputModule,
  MatListModule,
  MatNativeDateModule,
  MatSelectModule,
  MatSidenavModule,
  MatSnackBarModule,
  MatStepperModule,
  MatTableModule,
  MatToolbarModule,
  MatGridListModule,
  MatProgressSpinnerModule,
  MatTooltipModule,
  MatDatepickerModule,
  MatPaginatorModule,
  MatRadioModule,
  MatTabsModule,
  MatProgressBarModule,
  MatSortModule,
  MatIconModule,
  MatExpansionModule,
} from '@angular/material';
import { HttpClientModule } from '@angular/common/http';

@NgModule({
  declarations: [],
  imports: [
    CommonModule,
    MatButtonModule,
    MatToolbarModule,
    MatListModule,
    MatInputModule,
    MatFormFieldModule,
    MatSelectModule,
    MatCheckboxModule,
    MatSidenavModule,
    MatIconModule,
    MatMenuModule,
    MatSnackBarModule,
    MatCardModule,
    MatExpansionModule,
    MatTableModule,
    MatStepperModule,
    HttpClientModule,
    MatDialogModule,
    MatGridListModule,
    MatProgressSpinnerModule,
    MatTooltipModule,
    MatDatepickerModule,
    MatAutocompleteModule,
    MatPaginatorModule,
    MatRadioModule,
    MatNativeDateModule,
    MatTabsModule,
    MatSortModule,
    MatProgressBarModule,
  ],
  exports: [
    MatButtonModule,
    MatToolbarModule,
    MatListModule,
    MatInputModule,
    MatFormFieldModule,
    MatSelectModule,
    MatCheckboxModule,
    MatSidenavModule,
    MatIconModule,
    MatMenuModule,
    MatSnackBarModule,
    MatCardModule,
    MatExpansionModule,
    MatTableModule,
    MatStepperModule,
    HttpClientModule,
    MatDialogModule,
    MatGridListModule,
    MatProgressSpinnerModule,
    MatTooltipModule,
    MatDatepickerModule,
    MatAutocompleteModule,
    MatPaginatorModule,
    MatRadioModule,
    MatNativeDateModule,
    MatTabsModule,
    MatSortModule,
    MatProgressBarModule,
  ],
})
export class MaterialModule {}
